# Generated by Django 2.1.2 on 2018-11-15 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('phno', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='nomatch', message='length has to be 10', regex='^.{10}$')])),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='clientlist',
            unique_together={('name', 'phno', 'email')},
        ),
    ]
