# Generated by Django 2.1.2 on 2018-11-15 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklist',
            options={'ordering': ['created']},
        ),
        migrations.AlterUniqueTogether(
            name='mytodolist',
            unique_together={('title', 'due_date')},
        ),
        migrations.AlterUniqueTogether(
            name='tasklist',
            unique_together={('title', 'project_name')},
        ),
    ]
