# Generated by Django 2.1.2 on 2018-10-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20181009_2209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='recent_activity',
        ),
    ]
