# Generated by Django 2.1.2 on 2018-10-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0003_delete_recent_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='recent_activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=128)),
                ('task_done', models.CharField(max_length=128)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
