# Generated by Django 2.1.2 on 2018-10-13 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_recent_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recent_activity',
            old_name='date',
            new_name='dates',
        ),
        migrations.RenameField(
            model_name='recent_activity',
            old_name='time',
            new_name='times',
        ),
    ]
