# Generated by Django 2.0.6 on 2018-11-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(default='', max_length=100)),
                ('work_descript', models.TextField()),
                ('deadline', models.DateField(null=True)),
            ],
        ),
    ]
