# Generated by Django 2.0.6 on 2018-11-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_work_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_details',
            name='deadline',
            field=models.DateField(),
        ),
    ]
