# Generated by Django 2.0.6 on 2018-11-14 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_people_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='people_project',
        ),
        migrations.DeleteModel(
            name='work_details',
        ),
    ]
