# Generated by Django 2.0.6 on 2018-11-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_auto_20181114_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='people_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('work_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='work_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(default='', max_length=100)),
                ('work_descript', models.TextField()),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
